name: bwu_angular
version: 0.0.1
author: Günter Zöchbauer
description: Tools, decorators, or components we found useful for building AngularDart applications.
environment:
  sdk: '>=1.3.0 <2.0.0'
dependencies:
  angular: '>=0.10.0 <0.11.0'
  web_components: '>=0.3.3 <0.4.0'
  logging: '>=0.9.1+1 < 0.10.0'
